[main]
# Font settings
font=JetBrainsMonoNL Nerd Font Mono:size=8

# Window padding (X and Y axis)
pad=15x15

[colors-dark]
# Cursor colors format: <text-color> <cursor-color>
# Using your background color for the text, and your cursor color for the block
cursor=2E3440 81A1C1

# Note: foot uses hex codes without the '#' symbol
foreground=D8DEE9
background=2E3440
selection-foreground=D8DEE9
selection-background=d08770
urls=0087BD

# Normal/regular colors (black, red, green, yellow, blue, magenta, cyan, white)
regular0=3B4252
regular1=BF616A
regular2=A3BE8C
regular3=EBCB8B
regular4=81A1C1
regular5=B48EAD
regular6=88C0D0
regular7=E5E9F0

# Bright colors (black, red, green, yellow, blue, magenta, cyan, white)
bright0=4C566A
bright1=BF616A
bright2=A3BE8C
bright3=EBCB8B
bright4=81A1C1
bright5=B48EAD
bright6=8FBCBB
bright7=ECEFF4

[key-bindings]
clipboard-paste=Control+v
