general {
    lock_cmd = pidof hyprlock || hyprlock       # only execute hyprlock if not running
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on & brightnessctl -r  # turn on screen after sleep
}

listener {
    timeout = 60
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -s set 100%
}

listener {
    timeout = 120
    on-timeout = loginctl lock-session
    on-resume = brightnessctl -s set 100%
}

listener {
    timeout = 300
    # Lock the session AND turn off the screen
    on-timeout = hyprctl dispatch dpms off
    # Turn the screen back on when activity is detected
    on-resume = hyprctl dispatch dpms on & brightnessctl -s set 100%
}
